spring.application.name=backendparking

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/db_parking
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# ---Para swagger
springdoc.api-docs.path=/api-docs
# Ruta de la interfaz web de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html